"""empty message

Revision ID: 51900f0d4d57
Revises: dea0058bd203
Create Date: 2022-08-28 17:17:44.304958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51900f0d4d57'
down_revision = 'dea0058bd203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('color_label', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'color_label')
    # ### end Alembic commands ###
