"""empty message

Revision ID: 94523fdcf047
Revises: 3fc4d046251f
Create Date: 2022-08-28 12:21:16.905300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94523fdcf047'
down_revision = '3fc4d046251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_labels',
    sa.Column('tasks', sa.Integer(), nullable=False),
    sa.Column('labels', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['labels'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['tasks'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('tasks', 'labels')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
