"""empty message

Revision ID: dea0058bd203
Revises: 94523fdcf047
Create Date: 2022-08-28 12:43:53.469775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea0058bd203'
down_revision = '94523fdcf047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'labels', 'tasky_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_column('labels', 'user_id')
    # ### end Alembic commands ###
