"""empty message

Revision ID: 3fc4d046251f
Revises: ce9b71e888c4
Create Date: 2022-08-04 08:24:01.424550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc4d046251f'
down_revision = 'ce9b71e888c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('color_label', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_default')
    op.drop_column('projects', 'is_favorite')
    op.drop_column('projects', 'color_label')
    # ### end Alembic commands ###
